### ISSUE TITLE
What is autoload?

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-plugin-devtools#53]
When creating a new plugin, the devtools page uses a template that contains an `autoload` function. However this function fails, as the included folder does not exist by default. That confuses me.

I guess it makes most sense to:
* Remove this function
* Add the missing folder
* Or explain it inside the generated classes AND the tutorial

An autogenerated template that fails from the beginning is not a good start for new plugin devs.

**Comment by rhukster** [comment]
The instructions at the end of the 'new-plugin' command say to cd to the dir and run `composer install` to generate that plus the autoloader.

I think you missed this step.

The autoloader is useful to have because it's annoying to setup manually, and one mistake in the naming, can cause lots of headaches.  It's worth the one-time step of adding it.  If you don't use it you can remove the references after.

**Comment by NicoHood** [comment]
Okay, thanks for the fast feedback.

And what exactly is the autoloader? It is still unclear to me what it does and in which case it is needed. We might want to add this information here:
https://learn.getgrav.org/16/plugins/plugin-tutorial

**Comment by mahagr** [comment]
Autoloader makes sure that all the PHP classes get loaded on demand. It speeds up the code when the classes are not used and allows automatic testing to be performed to your code.

https://getcomposer.org/doc/

**Comment by rhukster** [comment]
i've made this clearer in the docs too.

**Comment by NicoHood** [comment]
In which docs? Do you have a link to the commit?
